set(SV_LIBS
  THIRDPARTY_METIS_SVFSI
  THIRDPARTY_PARMETIS_SVFSI
  THIRDPARTY_TETGEN
  THIRDPARTY_ZLIB
  SVFSILS)

foreach(lib ${SV_LIBS})
  string(TOLOWER "_SIMVASCULAR_${lib}" SV_LIB_${lib}_NAME)
endforeach()
