

set(SVFSILS_DEFINITIONS "")
set(SVFSILS_NEEDED_LIBS SVFSILS)

if(WIN32 OR (CYGWIN AND NOT IS64))
	#no SVFSILS for x32
endif()

if(LINUX AND IS64)
	#no SVFSILS for linux
endif()

if(IS64 AND (WIN32 OR CYGWIN))
unset(SVFSILS_INCLUDE_DIR)
	set(SVFSILS_PATH_PREFIX "SVFSILS-2013.08.10/win/x64")
	set(SVFSILS_FULL_PATH "${LicensedLibs_Bin_Directory}${SVFSILS_PATH_PREFIX}")
	set(SVFSILS_LIB_DIR "${SVFSILS_FULL_PATH}" CACHE TYPE PATH)
	set(SVFSILS_POSSIBLE_INCLUDE_DIR "${SVFSILS_FULL_PATH}" CACHE TYPE PATH)
endif()

find_path(SVFSILS_INCLUDE_DIR SVFSILS.h HINTS ${SVFSILS_POSSIBLE_INCLUDE_DIR})

GENLIBS(SVFSILS_LIBRARY "${SVFSILS_NEEDED_LIBS}" "SVFSILS" "${SVFSILS_LIB_DIR}")
set(SVFSILS_LIBRARY ${SVFSILS_SVFSILS_LIBRARY})

include_directories(${SVFSILS_INCLUDE_DIR})
link_directories(${SVFSILS_LIB_DIR})
add_definitions(${SVFSILS_DEFINITIONS})


